const PLAYER_WIDTH = 20;
const PLAYER_HEIGHT = 20;
const PLAYER_INIT_MOVING_SPEED = 2;
const PLAYER_MAX_MOVING_SPEED = 8;
const PLAYER_COLOR = '#AA0000'
const PLAYER_BULLET_SIZE = 10;
const PLAYER_BULLET_SPEED = 8;
const PLAYER_BULLET_COLOR = '#0000AA';